### ISSUE TITLE
ImportError: /cyvcf2/cyvcf2/cyvcf2.so: undefined symbol: EVP_sha1

### ISSUE THREAD

**Issue by mehar-GIT** [brentp/cyvcf2#121]
I am having the below issue while installing on ubuntu-18.04.1.

The below steps were run as per the instructions:

```
git clone --recursive https://github.com/brentp/cyvcf2
cd cyvcf2/htslib
autoheader
autoconf
./configure --enable-libcurl
make

cd ..
pip install -e .
```
Followed by:

```
```$ python3 setup.py test
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running test
Searching for nose
Best match: nose 1.3.7
Processing nose-1.3.7-py3.6.egg

Using /cyvcf2/.eggs/nose-1.3.7-py3.6.egg
running egg_info
writing cyvcf2.egg-info/PKG-INFO
writing dependency_links to cyvcf2.egg-info/dependency_links.txt
writing entry points to cyvcf2.egg-info/entry_points.txt
writing requirements to cyvcf2.egg-info/requires.txt
writing top-level names to cyvcf2.egg-info/top_level.txt
reading manifest file 'cyvcf2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cyvcf2.egg-info/SOURCES.txt'
running build_ext
skipping 'cyvcf2/cyvcf2.c' Cython extension (up-to-date)
/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/config.py:264: RuntimeWarning: Option 'with-coverage' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
Failure: ImportError (/cyvcf2/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1) ... ERROR

======================================================================
ERROR: Failure: ImportError (/cyvcf2/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/GQT/cyvcf2/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /cyvcf2/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1

----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>```

```
And

```
$ cyvcf2 --help
Traceback (most recent call last):
  File "/usr/local/bin/cyvcf2", line 11, in <module>
    load_entry_point('cyvcf2', 'console_scripts', 'cyvcf2')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/cyvcf2/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /cyvcf2/cyvcf2/cyvcf2.so: undefined symbol: EVP_sha1
```
Here i see a different python version is picked. However, the error in the above two cases is the same. Could someone assist to get this installed.

**Comment by brentp** [comment]
hi, make sure you have installled libcrypto and libssl (dev versions).

**Comment by mehar-GIT** [comment]
I have installed the below two packages (dev version is not found for libcrypto)

```
sudo apt-get install libcrypto++6
sudo apt-get install libssl-dev
```

Followed by:

```
$ sudo pip install -e .
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///cyvcf2
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from cyvcf2==0.11.4)
Installing collected packages: cyvcf2
  Found existing installation: cyvcf2 0.11.4
    Can't uninstall 'cyvcf2'. No files were found to uninstall.
  Running setup.py develop for cyvcf2
Successfully installed cyvcf2
```

Then the below command (only begining and last part of the error message is shown)

```
$ sudo python3 setup.py test
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running test
Searching for nose
Reading https://pypi.python.org/simple/nose/
........
........
........
/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/config.py:264: RuntimeWarning: Option 'with-coverage' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
Failure: ImportError (/cyvcf2/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1) ... ERROR

======================================================================
ERROR: Failure: ImportError (/cyvcf2/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/cyvcf2/.eggs/nose-1.3.7-py3.6.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/cyvcf2/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /cyvcf2/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so: undefined symbol: EVP_sha1

----------------------------------------------------------------------
Ran 1 test in 0.012s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
```

Could you help why it failed.

**Comment by brentp** [comment]
either your libcrypto is not install correctly, or you edited the setup.py or the setup so that if now fails. you may need to add `-lcrypto` to the setup.py
I would use python3.7 and/or try install via bioconda.

**Comment by mehar-GIT** [comment]
libcrypto installlation was successfull. I haven't changed the setup.py file. I now added the `-lcyrpto` in the below line. Is this correct place to add?

`libraries=['lcrypto', 'z', 'bz2', 'lzma', 'curl', 'ssl'] + (['crypt'] if platform.system() != 'Darwin' else []),`

**Comment by mehar-GIT** [comment]
OMG!!! the issue is with the htslib version that got cloned with the cyvcf2. I have replaced with the latest htslib and then the compilation worked like a charm. I hope it helps someone without killing the time.
