### ISSUE TITLE
libhts image not found

### ISSUE THREAD

**Issue by chadapohn** [brentp/cyvcf2#125]
`Traceback (most recent call last):
  File "/Volumes/Data1/pycli/pycli/vcf/test_cyvcf.py", line 1, in <module>
    from cyvcf2 import VCF
  File "/Users/proton/anaconda3/envs/pgx/lib/python3.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: dlopen(/Users/proton/anaconda3/envs/pgx/lib/python3.7/site-packages/cyvcf2/cyvcf2.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libdeflate.so
  Referenced from: /Users/proton/anaconda3/envs/pgx/lib/libhts.2.dylib
  Reason: image not found`

Please suggest me how to solve this error.

**Comment by CholoTook** [comment]
Can you give the output of `inxi -F` and explain how you installed cyvcf2?
