### ISSUE TITLE
cyvcf2.Writer + sys.stdout

### ISSUE THREAD

**Issue by cvlvxi** [brentp/cyvcf2#141]
Hi Brent,

Is there a way to get the writer to not write out to file but just to stdout?

I tried it by doing Writer(sys.stdout, my_vcf) and it fails  to the following..

```
(base) ➜  python git:(master) ✗ python gnomad.py
Traceback (most recent call last):
  File "gnomad.py", line 37, in <module>
    w = Writer(sys.stdout, f.vcf)
  File "cyvcf2/cyvcf2.pyx", line 2179, in cyvcf2.cyvcf2.Writer.__init__
  File "cyvcf2/cyvcf2.pyx", line 2144, in cyvcf2.cyvcf2.to_bytes
AttributeError: '_io.TextIOWrapper' object has no attribute 'encode'
```

Any recommendations?

**Comment by brentp** [comment]
"-" or "/dev/stdout" should work.

**Comment by cvlvxi** [comment]
Thanks
