### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by alanwilter** [brentp/cyvcf2#181]
I'm seeing a really awkward behaviour while installing `cyvcf2==0.30.1` (and even with earlier versions, depending on the host).

To reproduce the issue, using `docker`:
```bash
mkdir cytest
cd cytest
echo "FROM amazonlinux:latest" > Dockerfile
docker build -t cytest .
docker run --rm --name cytest -it cytest bash
```

Now, inside `docker`, do:

```bash
yum update -y
yum install -y --setopt install_weak_deps=false \
    bzip2-devel-1.0.6-13.amzn2.0.2 \
    gcc-7.3.1-9.amzn2 \
    libcurl-devel-7.61.1-12.amzn2.0.2 \
    make-3.82-24.amzn2 \
    openssl-devel-1.0.2k-19.amzn2.0.3 \
    python3-3.7.9-1.amzn2.0.1 python3-pip-9.0.3-1.amzn2.0.2 \
    python3-devel-3.7.9-1.amzn2.0.1 \
    python3-wheel-0.30.0a0-9.amzn2.0.3 \
    xz-devel-5.2.2-1.amzn2.0.2 \
    zlib-devel-1.2.7-18.amzn2

pip3 --no-cache-dir install --upgrade pip
pip --no-cache-dir install cyvcf2==0.30.1
```

and then, to test installation:

```python
bash-4.2# python3 -c "import cyvcf2; print(cyvcf2.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "cyvcf2/cyvcf2.pyx", line 1, in init cyvcf2.cyvcf2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
However, if I do force a reinstall (note: `--no-cache-dir` is critical here):
```python
bash-4.2# pip --no-cache-dir install cyvcf2==0.30.1 --force-reinstall
...
bash-4.2# python3 -c "import cyvcf2; print(cyvcf2.__version__)"
0.30.1
```
it works just fine.

What is going on here? Does anyone have an idea?

**Comment by alanwilter** [comment]
I still don't know why, but I found the culprit to be `wheel`, no matter if installed via `yum` or via `pip`.

**Comment by brentp** [comment]
so you likely know more about this than I, but this is something with numpy versions. Somehow your python is finding an old version.
Does this happen if you don't run from the cyvcf2 directory? from the traceback, it looks like it's finding a local cyvcf2/cyvc2.so but using the `__init__` from site-packages.

**Comment by alanwilter** [comment]
I have this here https://github.com/pypa/wheel/issues/391 that gives some suggestions about what to do at `cyvcf2` side.

**Comment by alanwilter** [comment]
It's working as of 0.30.4, thanks!

**Comment by pwwang** [comment]
This comes back with `0.30.15`.

```python
    from cyvcf2 import VCF
../../.cache/pypoetry/virtualenvs/vcfstats-o__EW0nK-py3.9/lib/python3.9/site-packages/cyvcf2/__init__.py:1: in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
cyvcf2/cyvcf2.pyx:1: in init cyvcf2.cyvcf2
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

with numpy `v1.21.1`. 

I am not sure if numpy is the culprit, but with numpy 1.22:

```shell
pip install numpy==1.22
```

The problem goes away.
