### ISSUE TITLE
Failing tests on ppc64el

### ISSUE THREAD

**Issue by nileshpatra** [brentp/cyvcf2#182]
Hi,

currently tests seem to fail on ppc64el, I'm not really sure about the issue here. Pasting the logs

```
python3.9 -m nose -v 
cyvcf2.tests.test_cli.test_version ... ok
make sure that we are getting the correct gt_types ... ok
cyvcf2.tests.test_reader.test_init ... ok
cyvcf2.tests.test_reader.test_type ... ok
cyvcf2.tests.test_reader.test_format_str ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_missing_samples ... ok
cyvcf2.tests.test_reader.test_ibd ... ok
cyvcf2.tests.test_reader.test_relatedness ... tested: 44 variants out of 115
ok
cyvcf2.tests.test_reader.test_pls ... ok
cyvcf2.tests.test_reader.test_gt_alt_freqs ... ok
cyvcf2.tests.test_reader.test_str ... ok
cyvcf2.tests.test_reader.test_region ... ok
cyvcf2.tests.test_reader.test_empty_info ... ok
cyvcf2.tests.test_reader.test_phases ... ok
cyvcf2.tests.test_reader.test_bad_init ... [E::hts_open_format] Failed to open file "XXXXX" : No such file or directory
ok
cyvcf2.tests.test_reader.test_samples ... ok
cyvcf2.tests.test_reader.test_next ... ok
cyvcf2.tests.test_reader.test_variant ... ok
cyvcf2.tests.test_reader.test_info_dict ... ok
cyvcf2.tests.test_reader.test_attrs ... ok
cyvcf2.tests.test_reader.test_empty ... ok
cyvcf2.tests.test_reader.test_format_field ... ok
cyvcf2.tests.test_reader.test_writer_from_string ... [W::vcf_parse] Contig 'chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_writer ... ok
cyvcf2.tests.test_reader.test_add_info_to_header ... ok
cyvcf2.tests.test_reader.test_read_flag ... ok
cyvcf2.tests.test_reader.test_add_flag ... ERROR
cyvcf2.tests.test_reader.test_constants ... ok
cyvcf2.tests.test_reader.test_add_filter_to_header ... ok
cyvcf2.tests.test_reader.test_seqnames ... ok
cyvcf2.tests.test_reader.test_different_index ... ok
cyvcf2.tests.test_reader.test_var_type ... ok
cyvcf2.tests.test_reader.test_header_info ... ok
cyvcf2.tests.test_reader.test_snpeff_header ... ok
cyvcf2.tests.test_reader.test_gt_types ... ok
cyvcf2.tests.test_reader.test_raw_header ... ok
cyvcf2.tests.test_reader.test_iterate ... ok
cyvcf2.tests.test_reader.test_empty_call ... ok
cyvcf2.tests.test_reader.test_haploid ... ok
cyvcf2.tests.test_reader.test_diploid ... ok
cyvcf2.tests.test_reader.test_format ... ok
cyvcf2.tests.test_reader.test_header_stuff ... ok
cyvcf2.tests.test_reader.test_bcf ... 
OK
no intervals found for b'/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_cyvcf2/build/cyvcf2/tests/test.snpeff.bcf' at 1:69260-69438
ok
cyvcf2.tests.test_reader.test_issue12 ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
Ensure gt_bases works with more complex base representations. ... ok
cyvcf2.tests.test_reader.test_set_format_float ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_format_int_a ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_format_int_b ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_format_int_c ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
test that we can handle multiple (in this case 3) values per sample ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_format_str_bytes_second_longer ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_format_str_bytes_first_longer ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_format_str_bytes_number3 ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_gts ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_info_del ... ok
cyvcf2.tests.test_reader.test_filter_id ... ok
cyvcf2.tests.test_reader.test_access_gts ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_access_genotype ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_access_genotype_array ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_alt_homozygous_gt ... ok
cyvcf2.tests.test_reader.test_write_missing_contig ... [W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_samples ... ok
cyvcf2.tests.test_reader.test_hrec ... ok
cyvcf2.tests.test_reader.test_issue44 ... ok
cyvcf2.tests.test_reader.test_id_field_updates ... ok
cyvcf2.tests.test_reader.test_set_pos ... ok
cyvcf2.tests.test_reader.test_set_chrom_when_contig_not_in_header ... [cyvcf2]: added new contig NEW to headerok
cyvcf2.tests.test_reader.test_set_chrom_after_contig_is_added_to_header ... ok
cyvcf2.tests.test_reader.test_set_qual ... ok
cyvcf2.tests.test_reader.test_strict_gt_option_flag ... ok
cyvcf2.tests.test_reader.test_alt_repr ... ok
cyvcf2.tests.test_reader.test_closed_iter ... ok
cyvcf2.tests.test_reader.test_issue72 ... ok
cyvcf2.tests.test_reader.test_is_transition ... ok
cyvcf2.tests.test_reader.test_decomposed ... ok
cyvcf2.tests.test_reader.test_fd ... ok
cyvcf2.tests.test_reader.test_set_reference ... ok
cyvcf2.tests.test_reader.test_set_alternates ... ok
cyvcf2.tests.test_reader.test_no_seqlen ... ok
cyvcf2.tests.test_reader.test_set_unknown_format ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithBcfFnameAndUncompressedMode_returnsUncompressedBcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithBcfFname_returnsCompressedBcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithCompressedBcfFname_returnsCompressedBcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithCompressedVcfFname_returnsCompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithHandle_returnsUncompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithIntFname_returnsUncompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithNonVcfName_returnsUncompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithPosixPath_returnsUncompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithStdOut_returnsUncompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_defaultModeWithVcfFname_returnsUncompressedVcf ... ok
cyvcf2.tests.test_writer.TestFileModeInference.test_explicitMode_doesNotInferFromFname ... ok

======================================================================
ERROR: cyvcf2.tests.test_reader.test_add_flag
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_cyvcf2/build/cyvcf2/tests/test_reader.py", line 344, in test_add_flag
    v = next(VCF(f))
  File "cyvcf2/cyvcf2.pyx", line 257, in cyvcf2.cyvcf2.VCF.__init__
    self._open_htsfile(fname, mode)
  File "cyvcf2/cyvcf2.pyx", line 192, in cyvcf2.cyvcf2.HTSFile._open_htsfile
    raise IOError(
OSError: /tmp/tmpwa82u_uo.vcf is not valid bcf or vcf (format: 15 mode: r)

----------------------------------------------------------------------
```

**Comment by nileshpatra** [comment]
@brentp could you please take a look?

**Comment by brentp** [comment]
I think @nh13 wrote the code to allow use of file-handles, that's also where we have problems with #187 . Any ideas?

**Comment by nileshpatra** [comment]
Hi @brentp 

> I think @nh13 wrote the code to allow use of file-handles, that's also where we have problems with #187 . Any ideas?

I've no clue. From what I gathered, according to you, is the fix opening the file with "rb" mode?
It'd be nice if it could be fixed, though.

**Comment by nh13** [comment]
I can take a look, but don’t have access to such a computer.

**Comment by brentp** [comment]
@nileshpatra can you test #188 on your system?
