### ISSUE TITLE
Hangs and/or errors using cyvcf2 inside a multiprocessing pool

### ISSUE THREAD

**Issue by grahamgower** [brentp/cyvcf2#233]
I'm trying to sample random regions of a vcf file, and using multiprocessing to do this in parallel. However, it looks like something is non-reentrant. But that doesn't make sense, because these are processes, not threads, so I'm not sure what's going on here. Non-parallel sampling works fine.

```python
# mre.py
import multiprocessing

import numpy as np
import cyvcf2


print("numpy", np.__version__)
print("cyvcf2", cyvcf2.__version__)
print()

# High coverage whole genome sequencing of the expanded 1000 Genomes Project cohort including 602 trios.
# paper: https://www.biorxiv.org/content/10.1101/2021.02.06.430068v2
# data: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/
file = "CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz"
# Some YRI samples. Just chosen for testing.
samples = ["NA18486", "NA18487", "NA18488", "NA18489", "NA18498", "NA18499", "NA18501"]
vcf = cyvcf2.VCF(file, samples=samples, lazy=True, threads=None)


def sample_regions(
    rng, size, contig_id="chr21", contig_length=46709983, sequence_length=1_000_000
):
    """Return a list of random regions of length `sequence_length`."""
    upper_limit = contig_length - sequence_length
    start = 1 + rng.integers(low=0, high=upper_limit, size=size, endpoint=True)
    end = start + sequence_length - 1
    return list(zip([contig_id] * size, start, end))


def get_genotype_matrix(vcf: cyvcf2.VCF, *, chrom: str, start: int, end: int):
    """Get a genotype matrix for the specified genomic window."""
    G = []
    for variant in vcf(f"{chrom}:{start}-{end}"):
        if not variant.is_snp:
            continue
        a = variant.genotype.array()
        gt = a[:, :-1]
        G.append(gt)

    try:
        np_G = np.array(G, dtype=np.int8)
    except ValueError as e:
        # Most likely an "inhomogeneous shape" error, caused by different
        # ploidies at different sites. Catch and reraise to provide
        # a more user-friendly error message.
        raise ValueError(
            f"Mismatched ploidy among sites in {chrom}:{start}-{end}."
        ) from e

    return np_G


def sample_vcf(region):
    contig, start, end = region
    return get_genotype_matrix(vcf, chrom=contig, start=start, end=end)


def run(seed=1234, num_reps=8):
    rng = np.random.default_rng(seed)
    regions = sample_regions(rng, size=num_reps)
    for contig, start, end in regions:
        print(contig, start, end)
    print()
    pool = multiprocessing.Pool(processes=8)
    matrices = []
    print("calling sample_vcf()")
    for j, G in enumerate(pool.imap(sample_vcf, regions)):
        print(j, "of", num_reps)
        matrices.append(G)
    print("done")


if __name__ == "__main__":
    run()
```

On my 4 core (8 hyperthreads) laptop, I get the following output and a deadlock (reproducible):
```
$ python mre.py
numpy 1.21.4
cyvcf2 0.30.14

chr21 44766109 45766108
chr21 44644931 45644930
chr21 45158749 46158748
chr21 17378741 18378740
chr21 7832855 8832854
chr21 42201571 43201570
chr21 4794642 5794641
chr21 11961957 12961956

calling sample_vcf()
[E::bgzf_uncompress] Inflate operation failed: 3
[E::bgzf_read_block] Invalid BGZF header at offset 464039648
[E::bgzf_uncompress] Inflate operation failed: 1
[E::bgzf_read_block] Invalid BGZF header at offset 98293461
[E::bgzf_uncompress] Inflate operation failed: 1
[E::bgzf_read_block] Invalid BGZF header at offset 472457838
[E::bgzf_uncompress] Inflate operation failed: 1
[E::bgzf_read_block] Invalid BGZF header at offset 466383486
[E::bgzf_uncompress] Inflate operation failed: 1
[E::bgzf_read_block] Invalid BGZF header at offset 434396413
0 of 8
1 of 8
2 of 8
3 of 8
[E::bgzf_uncompress] Inflate operation failed: 3
[E::vcf_parse_format] Number of columns at chr21:7915807 does not match the number of samples (0 vs 7)
[E::bgzf_read_block] Invalid BGZF header at offset 10644
[E::vcf_parse_format] Number of columns at chr21:5030596 does not match the number of samples (0 vs 7)
```

Changing the `cyvcf2.VCF()` call to use `threads=1` triggers an immediate deadlock of the processing pool:
```
$ python mre.py
numpy 1.21.4
cyvcf2 0.30.14

chr21 44766109 45766108
chr21 44644931 45644930
chr21 45158749 46158748
chr21 17378741 18378740
chr21 7832855 8832854
chr21 42201571 43201570
chr21 4794642 5794641
chr21 11961957 12961956

calling sample_vcf()
```

Using a regular `map()` instead of a mulitprocessing pool completes successfully (for both `threads=1` and `threads=None`).
```
$ python mre.py
numpy 1.21.4
cyvcf2 0.30.14

chr21 44766109 45766108
chr21 44644931 45644930
chr21 45158749 46158748
chr21 17378741 18378740
chr21 7832855 8832854
chr21 42201571 43201570
chr21 4794642 5794641
chr21 11961957 12961956

calling sample_vcf()
0 of 8
1 of 8
2 of 8
3 of 8
4 of 8
5 of 8
6 of 8
7 of 8
done
```

**Comment by brentp** [comment]
This can't work with threads or processes in any language. 
Each thread would move the file pointer.
You would need to open a new `VCF` object for each process or thread.

**Comment by grahamgower** [comment]
So the VCF object doesn't get automatically duplicated when the pool does its own forking? I must be missing something obvious here.

**Comment by brentp** [comment]
No. try this same exercise with a python file object and you'll encounter the same problem, right?

**Comment by tomwhite** [comment]
FWIW I've managed to use cyvcf2 to read VCFs using threads and processes successfully. This is using Dask, where the distributed scheduler gives the best performance: https://pystatgen.github.io/sgkit/latest/vcf.html#example-converting-1000-genomes-vcf-to-zarr

**Comment by grahamgower** [comment]
> No. try this same exercise with a python file object and you'll encounter the same problem, right?

Right you are. Thanks!
```python
import multiprocessing
import os

def foo(args):
    fd, j = args
    f = os.fdopen(fd)
    if j == 0:
        f.seek(100)
    return f.tell()

file = open("/etc/passwd")

def run(num_reps=8):
    args = zip([file.fileno()] * num_reps, range(num_reps))
    pool = multiprocessing.Pool(processes=8)
    for j, pos in enumerate(pool.imap(foo, args)):
        print(j, pos)

if __name__ == "__main__":
    run()
```

```
$ python pool.py
0 100
1 100
2 100
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/grg/miniconda3/envs/cyvcf2/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "pool.py", line 6, in foo
    f = os.fdopen(fd)
  File "/home/grg/miniconda3/envs/cyvcf2/lib/python3.7/os.py", line 1029, in fdopen
    return io.open(fd, *args, **kwargs)
OSError: [Errno 9] Bad file descriptor
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pool.py", line 20, in <module>
    run()
  File "pool.py", line 16, in run
    for j, pos in enumerate(pool.imap(foo, args)):
  File "/home/grg/miniconda3/envs/cyvcf2/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
OSError: [Errno 9] Bad file descriptor
```

**Comment by grahamgower** [comment]
> FWIW I've managed to use cyvcf2 to read VCFs using threads and processes successfully. This is using Dask, where the distributed scheduler gives the best performance: https://pystatgen.github.io/sgkit/latest/vcf.html#example-converting-1000-genomes-vcf-to-zarr

That looks cool. I don't know what a Dask is though (and it looks complicated), so for now I'll just fix my code.
