### ISSUE TITLE
Single Sample VCF errors with because .n_samples is not calculated properly?

### ISSUE THREAD

**Issue by danielecook** [brentp/cyvcf2#48]
Hope this helps! 

The VCF below throws an error. It has a single sample. Trigger the error by running:

```
from cyvcf2 import VCF
v = VCF("in.vcf")
for record in v:
    record.gt_bases()
```
__Results in:__
```
ValueError: range() step argument must not be zero
```

__Traceback - slightly different code; but same idea__
```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/var/pyenv/versions/2.7.11/envs/cendr/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/Users/dancook/Documents/git/cendr/cendr/views/api/variant.py", line 93, in variant_api
    gt_set = zip(v.samples, record.gt_bases.tolist(), record.gt_types.tolist(), record.format("FT").tolist())
  File "cyvcf2/cyvcf2.pyx", line 942, in cyvcf2.cyvcf2.Variant.gt_bases.__get__ (cyvcf2/cyvcf2.c:22323)
```
__The offending line__
https://github.com/brentp/cyvcf2/blob/master/cyvcf2/cyvcf2.pyx#L942

```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=I,length=15072434>
##contig=<ID=II,length=15279421>
##contig=<ID=III,length=13783801>
##contig=<ID=IV,length=17493829>
##contig=<ID=V,length=20924180>
##contig=<ID=X,length=17718942>
##contig=<ID=MtDNA,length=13794>
##FILTER=<ID=dv_dp,Description="Set if not true: (FORMAT/AD[1])/(FORMAT/DP) >= 0.5 || FORMAT/GT == '0/0'">
##FILTER=<ID=het,Description="Set if true: AC==1">
##FILTER=<ID=high_heterozygosity,Description="Apply filter if FREQUENCY(HET) > 0.1">
##FILTER=<ID=high_missing,Description="Apply filter if FREQUENCY(MISSING) > 0.9">
##FILTER=<ID=mapping_quality,Description="Set if not true: INFO/MQ > 40">
##FILTER=<ID=min_depth,Description="Set if not true: FORMAT/DP > 10">
##FILTER=<ID=quality,Description="Set if not true: QUAL >= 30 || FORMAT/GT == '0/0'">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Total number of alternate alleles in called genotypes">
##INFO=<ID=AD,Number=R,Type=Integer,Description="Total allelic depths">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##INFO=<ID=ANN,Number=.,Type=String,Description="Functional annotations: 'Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO'">
##INFO=<ID=BQB,Number=1,Type=Float,Description="Mann-Whitney U test of Base Quality Bias (bigger is better)">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Raw read depth">
##INFO=<ID=DP4,Number=4,Type=Integer,Description="Number of high-quality ref-forward , ref-reverse, alt-forward and alt-reverse bases">
##INFO=<ID=HOB,Number=1,Type=Float,Description="Bias in the number of HOMs number (smaller is better)">
##INFO=<ID=ICB,Number=1,Type=Float,Description="Inbreeding Coefficient Binomial test (bigger is better)">
##INFO=<ID=IDV,Number=1,Type=Integer,Description="Maximum number of reads supporting an indel">
##INFO=<ID=IMF,Number=1,Type=Float,Description="Maximum fraction of reads supporting an indel">
##INFO=<ID=INDEL,Number=0,Type=Flag,Description="Indicates that the variant is an INDEL.">
##INFO=<ID=LOF,Number=.,Type=String,Description="Predicted loss of function effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
##INFO=<ID=MQ,Number=1,Type=Integer,Description="Average mapping quality">
##INFO=<ID=MQ0F,Number=1,Type=Float,Description="Fraction of MQ0 reads (smaller is better)">
##INFO=<ID=MQB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality Bias (bigger is better)">
##INFO=<ID=MQSB,Number=1,Type=Float,Description="Mann-Whitney U test of Mapping Quality vs Strand Bias (bigger is better)">
##INFO=<ID=NMD,Number=.,Type=String,Description="Predicted nonsense mediated decay effects for this variant. Format: 'Gene_Name | Gene_ID | Number_of_transcripts_in_gene | Percent_of_transcripts_affected'">
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=RPB,Number=1,Type=Float,Description="Mann-Whitney U test of Read Position Bias (bigger is better)">
##INFO=<ID=SGB,Number=1,Type=Float,Description="Segregation based metric.">
##INFO=<ID=VDB,Number=1,Type=Float,Description="Variant Distance Bias for filtering splice-site artefacts in RNA-seq data (bigger is better)",Version="3">
##INFO=<ID=phastcons,Number=1,Type=String,Description="calculated by self of overlapping values in column 4 from phastcons.bed.gz">
##INFO=<ID=phylop,Number=1,Type=String,Description="calculated by self of overlapping values in column 4 from phylop.bed.gz">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths">
##FORMAT=<ID=ADF,Number=R,Type=Integer,Description="Allelic depths on the forward strand">
##FORMAT=<ID=ADR,Number=R,Type=Integer,Description="Allelic depths on the reverse strand">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Number of high-quality bases">
##FORMAT=<ID=FT,Number=1,Type=String,Description="Genotype-level filter">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=HP,Number=1,Type=String,Description="Flag used to mark whether a variant was polarized">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
##FORMAT=<ID=SP,Number=1,Type=Integer,Description="Phred-scaled strand bias P-value">
##samtoolsVersion=1.3.1+htslib-1.3.2
##samtoolsCommand=samtools mpileup --redo-BAQ -r I --BCF --output-tags DP,AD,ADF,ADR,INFO/AD,SP --fasta-ref /projects/b1059/data/genomes/c_elegans/WS245/WS245.fa.gz QG556.bam
##reference=file:///projects/b1059/data/genomes/c_elegans/WS245/WS245.fa.gz
##ALT=<ID=*,Description="Represents allele(s) other than observed.">
##bcftools_callVersion=1.3.1+htslib-1.3.2
##bcftools_callCommand=call -T sitelist.tsv.gz --skip-variants indels --multiallelic-caller -O z -
##bcftools_concatVersion=1.3.1+htslib-1.3.2
##bcftools_concatCommand=concat -O v QG556.I.union.vcf.gz QG556.II.union.vcf.gz QG556.III.union.vcf.gz QG556.IV.union.vcf.gz QG556.V.union.vcf.gz QG556.X.union.vcf.gz QG556.MtDNA.union.vcf.gz
##VCF-kit(version 0.1.2) command=geno het-polarization
##bcftools_filterVersion=1.3.1+htslib-1.3.2
##bcftools_filterCommand=filter -O u --threads 6 --mode + --soft-filter quality --include 'QUAL >= 30 || FORMAT/GT == '0/0''
##bcftools_filterCommand=filter -O u --threads 6 --mode + --soft-filter min_depth --include 'FORMAT/DP > 10'
##bcftools_filterCommand=filter -O u --threads 6 --mode + --soft-filter mapping_quality --include 'INFO/MQ > 40'
##bcftools_filterCommand=filter -O u --threads 6 --mode + --soft-filter dv_dp --include '(FORMAT/AD[1])/(FORMAT/DP) >= 0.5 || FORMAT/GT == '0/0''
##bcftools_filterCommand=filter --mode + --soft-filter het --exclude AC==1
##bcftools_viewVersion=1.3.1+htslib-1.3.2
##bcftools_viewCommand=view -O z
##bcftools_mergeVersion=1.3.1+htslib-1.3.2
##bcftools_mergeCommand=merge --threads 16 --regions I -O z -m all --file-list union_vcfs.txt
##bcftools_concatCommand=concat -O z I.merged.raw.vcf.gz II.merged.raw.vcf.gz III.merged.raw.vcf.gz IV.merged.raw.vcf.gz V.merged.raw.vcf.gz X.merged.raw.vcf.gz MtDNA.merged.raw.vcf.gz
##bcftools_viewCommand=view merged.raw.vcf.gz
##bcftools_viewCommand=view -O z -
##bcftools_viewVersion=1.4+htslib-1.4
##bcftools_viewCommand=view -O v merged.filtered.vcf.gz; Date=Mon Apr  3 22:03:56 2017
##SnpEffVersion="4.2 (build 2015-12-05), by Pablo Cingolani"
##SnpEffCmd="SnpEff  -no-downstream -no-intergenic -no-upstream WS258 "
##bcftools_viewCommand=view -O z; Date=Mon Apr  3 22:04:04 2017
##bcftools_viewCommand=view -O z; Date=Mon Apr  3 22:38:00 2017
##bcftools_viewVersion=1.3+htslib-1.3
##bcftools_viewCommand=view --force-samples --samples CB4856 http://storage.googleapis.com/elegansvariation.org/releases/20170312/WI.20170312.vcf.gz II:14524173-14525112
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	CB4856
II	14524236	.	C	T	999	PASS	AC=0;AD=0,65;AF=0.294872;AN=2;BQB=0.555202;DP=15777;DP4=4011,6019,1703,2364;HOB=0.5;ICB=1;MQ=60;MQ0F=0;MQB=1;MQSB=1;NS=234;RPB=0.514647;SGB=-0.693147;VDB=0.549834;ANN=T|synonymous_variant|LOW|WBGene00010195|WBGene00010195|transcript|F57C2.3|protein_coding|1/3|c.42C>T|p.Phe14Phe|64/844|42/756|14/251||;phastcons=0.25;phylop=0.582	GT:DP:SP:ADF:ADR:AD:FT:PL:HP	0/0:55:0:42,.:13,.:55,.:PASS:.:.
II	14524299	.	G	A	999	PASS	AC=0;AD=0,65;AF=0.25;AN=2;BQB=0.958856;DP=20099;DP4=8769,3477,3191,1393;HOB=0.5;ICB=1;MQ=60;MQ0F=0;MQB=1;MQSB=1;NS=234;RPB=0.436914;SGB=-0.693147;VDB=1.69288e-07;ANN=A|synonymous_variant|LOW|WBGene00010195|WBGene00010195|transcript|F57C2.3|protein_coding|1/3|c.105G>A|p.Ser35Ser|127/844|105/756|35/251||;phastcons=0.25;phylop=-0.256	GT:DP:SP:ADF:ADR:AD:FT:PL:HP	0/0:87:0:71,.:16,.:87,.:PASS:.:.
II	14524396	.	T	A	999	PASS	AC=0;AD=99,25;AF=0.0769231;AN=2;BQB=1;DP=19446;DP4=10712,5058,1001,485;MQ=60;MQ0F=0;MQB=1;MQSB=1;NS=234;RPB=1;SGB=-0.692914;VDB=0.58164;ANN=A|missense_variant|MODERATE|WBGene00010195|WBGene00010195|transcript|F57C2.3|protein_coding|1/3|c.202T>A|p.Phe68Ile|224/844|202/756|68/251||;phastcons=0.25;phylop=0.702	GT:DP:SP:ADF:ADR:AD:FT:PL	0/0:70:0:50,.:20,.:70,.:PASS:.
```

**Comment by brentp** [comment]
I'm not getting that error using your pasted VCF and the current cyvcf2

**Comment by danielecook** [comment]
hmm okay i'll take another look. Sorry for the trouble. The error was being thrown at that record but maybe there was something weird going on with the following lines that I removed.

**Comment by danielecook** [comment]
This was a stupid mistake on my part - I wasn't flushing a file when writing and was trying to read it before it was output. Very sorry again for wasting your time.

**Comment by brentp** [comment]
no problem! let me know if you hit any other issues.
