### ISSUE TITLE
Any changes done to htslib? vcf.c assertion error in test

### ISSUE THREAD

**Issue by smoe** [brentp/cyvcf2#91]
Hello,

I am experimenting to build cyvcf2 010 with the official htslib 1.8 release (there is also 1.9 since 8 days on https://github.com/samtools/htslib/releases) distributed in debian/experimental since I understand from looking at htslib/version* that this is what you are using. Do have performed any changes to that external code base?

I am asking since I ran into an assertion in vcf.c:
```
.... many tests ok ...
cyvcf2.tests.test_reader.test_header_stuff ... ok
cyvcf2.tests.test_reader.test_bcf ... 
OK
no intervals found for /home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test.snpeff.bcf at 1:69260-69438
ok
cyvcf2.tests.test_reader.test_issue12 ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_gt_bases_nondiploid
Ensure gt_bases works with more complex base representations. ... ok
cyvcf2.tests.test_reader.test_set_format_float ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:567: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PS", np.array([0.555, 1.111], dtype=np.float))
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:567: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  v.set_format("PS", np.array([0.555, 1.111], dtype=np.float))
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:570: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PS", np.array([8.555, 11.111], dtype=np.float64))
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:570: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  v.set_format("PS", np.array([8.555, 11.111], dtype=np.float64))
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:573: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PS", np.array([9998.555, 99911.111], dtype=np.float32))
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:573: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  v.set_format("PS", np.array([9998.555, 99911.111], dtype=np.float32))
ok
cyvcf2.tests.test_reader.test_set_format_int ... [W::vcf_parse] Contig '7' is not defined in the header. (Quick workaround: index the file with tabix.)
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:581: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PI", np.array([5, 1], dtype=np.int))
/home/moeller/git/debian-med/cyvcf2/cyvcf2/tests/test_reader.py:584: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  v.set_format("PI", np.array([855, 11], dtype=np.int64))
python2.7: vcf.c:3482: bcf_update_format: Assertion `!fmt->p_free' failed.
Aborted (core dumped)
E: pybuild pybuild:338: test: plugin distutils failed with: exit code=134: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
```
Please apologize if you have made any statement already on what you have changed in the source tree if any.  I had not found it. 

Cheers,

Steffen

**Comment by brentp** [comment]
Hi, can you clarify what you are doing? did you change the contents of htslib/ ? or you are just unable to build after my recent update to htslib?

**Comment by smoe** [comment]
Hi,

Thank you for your quick reply. I am one of the individuals who contributed to the packaging of cyvcf2 for Debian as it is used within the bcbio workflow that we are after. I should mention  @LiubovCh who is kindly working towards the same aims along these dependencies. I just saw your exchange on https://github.com/brentp/cyvcf2/issues/89. 

There is a policy in Debian that says that packages should share libraries to avoid code duplication and help finding bugs. That is why I have removed your htslib directory from the local source tree. The package builds until it reaches that point described in my initial post.

I just tried again with your official code base. Here I run into a missing symbol for testing:
```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-jgBwco/python2.7-2.7.15=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-z,relro -g -O2 -fdebug-prefix-map=/home/moeller/git/debian-med/cyvcf2-0.10.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-2.7/cyvcf2/cyvcf2.o build/temp.linux-x86_64-2.7/htslib/knetfile.o build/temp.linux-x86_64-2.7/htslib/bcf_sr_sort.o build/temp.linux-x86_64-2.7/htslib/vcfutils.o build/temp.linux-x86_64-2.7/htslib/md5.o build/temp.linux-x86_64-2.7/htslib/hfile_s3.o build/temp.linux-x86_64-2.7/htslib/thread_pool.o build/temp.linux-x86_64-2.7/htslib/vcf.o build/temp.linux-x86_64-2.7/htslib/hfile_net.o build/temp.linux-x86_64-2.7/htslib/hfile_libcurl.o build/temp.linux-x86_64-2.7/htslib/hfile_gcs.o build/temp.linux-x86_64-2.7/htslib/t.o build/temp.linux-x86_64-2.7/htslib/faidx.o build/temp.linux-x86_64-2.7/htslib/regidx.o build/temp.linux-x86_64-2.7/htslib/tbx.o build/temp.linux-x86_64-2.7/htslib/multipart.o build/temp.linux-x86_64-2.7/htslib/hts_os.o build/temp.linux-x86_64-2.7/htslib/kfunc.o build/temp.linux-x86_64-2.7/htslib/bgzf.o build/temp.linux-x86_64-2.7/htslib/errmod.o build/temp.linux-x86_64-2.7/htslib/kstring.o build/temp.linux-x86_64-2.7/htslib/hts.o build/temp.linux-x86_64-2.7/htslib/synced_bcf_reader.o build/temp.linux-x86_64-2.7/htslib/sam.o build/temp.linux-x86_64-2.7/htslib/realn.o build/temp.linux-x86_64-2.7/htslib/hfile.o build/temp.linux-x86_64-2.7/htslib/textutils.o build/temp.linux-x86_64-2.7/htslib/vcf_sweep.o build/temp.linux-x86_64-2.7/htslib/probaln.o build/temp.linux-x86_64-2.7/htslib/cram/cram_external.o build/temp.linux-x86_64-2.7/htslib/cram/cram_samtools.o build/temp.linux-x86_64-2.7/htslib/cram/cram_decode.o build/temp.linux-x86_64-2.7/htslib/cram/cram_stats.o build/temp.linux-x86_64-2.7/htslib/cram/mFILE.o build/temp.linux-x86_64-2.7/htslib/cram/pooled_alloc.o build/temp.linux-x86_64-2.7/htslib/cram/cram_encode.o build/temp.linux-x86_64-2.7/htslib/cram/string_alloc.o build/temp.linux-x86_64-2.7/htslib/cram/rANS_static.o build/temp.linux-x86_64-2.7/htslib/cram/cram_io.o build/temp.linux-x86_64-2.7/htslib/cram/open_trace_file.o build/temp.linux-x86_64-2.7/htslib/cram/cram_codecs.o build/temp.linux-x86_64-2.7/htslib/cram/cram_index.o build/temp.linux-x86_64-2.7/htslib/cram/sam_header.o build/temp.linux-x86_64-2.7/htslib/cram/files.o build/temp.linux-x86_64-2.7/cyvcf2/helpers.o -lz -lcurl -o /home/moeller/git/debian-med/cyvcf2-0.10.0/cyvcf2/cyvcf2.so
/usr/lib/python2.7/dist-packages/nose/config.py:264: RuntimeWarning: Option 'with-coverage' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
Failure: ImportError (/home/moeller/git/debian-med/cyvcf2-0.10.0/cyvcf2/cyvcf2.so: undefined symbol: EVP_sha1) ... ERROR

======================================================================
ERROR: Failure: ImportError (/home/moeller/git/debian-med/cyvcf2-0.10.0/cyvcf2/cyvcf2.so: undefined symbol: EVP_sha1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/moeller/git/debian-med/cyvcf2-0.10.0/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
ImportError: /home/moeller/git/debian-med/cyvcf2-0.10.0/cyvcf2/cyvcf2.so: undefined symbol: EVP_sha1

----------------------------------------------------------------------
Ran 1 test in 0.019s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
E: pybuild pybuild:338: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
make: *** [debian/rules:9: binary] Error 25
moeller@steffen-laptop-debian:~/git/debian-med/cyvcf2-0.10.0$ locate EVP_sha1
moeller@steffen-laptop-debian:~/git/debian-med/cyvcf2-0.10.0$ find .^C
moeller@steffen-laptop-debian:~/git/debian-med/cyvcf2-0.10.0$ grep -ri !$ .
grep -ri EVP_sha1 .
./htslib/hfile_s3.c:    HMAC(EVP_sha1(), key->s, key->l,
Binary file ./build/temp.linux-x86_64-3.6/htslib/hfile_s3.o matches
Binary file ./build/temp.linux-x86_64-2.7/htslib/hfile_s3.o matches
Binary file ./build/temp.linux-x86_64-3.7/htslib/hfile_s3.o matches
Binary file ./cyvcf2/cyvcf2.so matches
Binary file ./.pybuild/cpython2_2.7_cyvcf2/build/cyvcf2/cyvcf2.so matches
Binary file ./.pybuild/cpython3_3.7_cyvcf2/build/cyvcf2/cyvcf2.cpython-37m-x86_64-linux-gnu.so matches
Binary file ./.pybuild/cpython3_3.6_cyvcf2/build/cyvcf2/cyvcf2.cpython-36m-x86_64-linux-gnu.so
```
@LiubovCh, did you encounter something along those lines?

Many thanks to you both.

Steffen

**Comment by smoe** [comment]
Hello again,

I bit of googling made me add 'ssl','crypt' to your list of libraries. This was successful.  I am now where also @LiubovCh is:

```
cyvcf2.tests.test_reader.test_alt_homozygous_gt ... ok
cyvcf2.tests.test_reader.test_write_missing_contig ... [W::vcf_parse] Contig '1' is not defined in the header. (Quick workaround: index the file with tabix.)
ok
cyvcf2.tests.test_reader.test_set_samples ... ok
cyvcf2.tests.test_reader.test_hrec ... ok
cyvcf2.tests.test_reader.test_issue44 ... FAIL

======================================================================
FAIL: cyvcf2.tests.test_reader.test_issue44
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/moeller/git/debian-med/cyvcf2-0.10.0/cyvcf2/tests/test_reader.py", line 712, in test_issue44
    assert v.genotypes == [expected[i]], (i, v.genotypes, expected[i])
AssertionError: (1, [[-1, True]], [-1, False])
    #print(v.genotypes, file=sys.stderr)
>>  assert Variant(2:176938647 A/G).genotypes == [[[-1, -1, False], [-1, False], [-1, -1, True], [0, 0, True]][1]], (1, Variant(2:176938647 A/G).genotypes, [[-1, -1, False], [-1, False], [-1, -1, True], [0, 0, True]][1])
    

----------------------------------------------------------------------
Ran 55 tests in 1.349s

FAILED (failures=1)
Test failed: <unittest.runner.TextTestResult run=55 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=55 errors=0 failures=1>
E: pybuild pybuild:338: test: plugin distutils failed with: exit code=1: python2.7 setup.py test 
dh_auto_test: pybuild --test -i python{version} -p 2.7 returned exit code 13
make: *** [debian/rules:9: binary] Error 25
```

I will hence check out your master branch with the patch https://github.com/brentp/cyvcf2/commit/6a3a51d97ef1847b011e53b2ee3d0c32298dec44 you referenced in her issue https://github.com/brentp/cyvcf2/issues/89 about it, try again and report. Anyway, I would be interested if you happen to have any idea why I run into the assert with the external library :)

**Comment by smoe** [comment]
Using the deb-fix branch, when
 * renaming your package's htslib to htslib-renamed
 * installing "apt-get -t experimental install libhts-dev" (which gets version 1.8)
 * adding the hts library to link against
```
--- a/setup.py
+++ b/setup.py
@@ -66,7 +66,7 @@ from Cython.Distutils import build_ext
 cmdclass = {'build_ext': build_ext}
 extension = [Extension("cyvcf2.cyvcf2",
                         ["cyvcf2/cyvcf2.pyx"] + sources,
-                        libraries=['z', 'curl', 'ssl', 'crypt'],
+                        libraries=['hts', 'z', 'curl', 'ssl', 'crypt'],
                         include_dirs=['htslib', 'cyvcf2', np.get_include()])]
```
when testing I run into the same
```
python2.7: vcf.c:3482: bcf_update_format: Assertion `!fmt->p_free' failed.
Aborted (core dumped)
```
If you have done no changes to htslib then the problem could be caused from using a dynamic instead of the static library that I understand you create. 

If that is of any help, I happily grant you access to a Debian machine to experience the problem first-hand. No worries - I just set one up with some cheapish cloud offer and add whatever public ssh key you want me to add.

**Comment by smoe** [comment]
I have added -fPIC to the libhts.a build. cyvcv2.so then needed lzma and bz2 as extra libraries. The error however prevailed.

I looked that line up in the htslib source tree:
```
$ grep _free vcf.c |grep assert
            assert( !inf->vptr_free );  // fix the caller or improve here: this has been modified before
            assert( !fmt->p_free );  // fix the caller or improve here: this has been modified before
```

So something is going on over there that upstream knows about. The same asserts are still found in htslib 1.9. 

And since I was in the official htslib trees anyway, I then also tried to answer my initial question with a
`for i in *.c; do echo $i:; diff $i ../cyvcf2-github/htslib-renamed/$i; done`. What I see is kind of what I expected. Given that delta, Debian's code-sharing policy should be overridden for scientific reasons and the htslib directory be used that you redistribute, instead. @LiubovCh, do you agree?

To help communicating your issues back, and keep your code structure intact, it may help to present your subdirectory as a [git ubmodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules). That submodule would then refer to a **_fork_** of yours of the [original htslib code](https://github.com/samtools/htslib). I think then we have everything - Debian's principles of having projects work on the same code base as much as possible are supported as good as it now gets, everything is scientifically well documented with the help of github, and we have a working package without much extra hassle.

**Comment by brentp** [comment]
I think I can get a debian env set up if not, I'll take you up on that. I agree that a submodule would be the way to go. I think I can get it to use the default htslib, just need to add more options and machinery to the setup.py. I'll give that a try over the next week and get back to you.

thanks again for digging into this.

**Comment by LiubovCh** [comment]
Hi,
@smoe, I apologize for missing some previous questions to me! 

> @LiubovCh, did you encounter something along those lines?

Yes, this is the very same failure I was stuck with and found it too tricky for me to solve, because as you noticed:

> something is going on over there that upstream knows about. 

I admit I just did not know how to deal with such a problem concerning Debian policy and I totally agree with both of you that a submodule would be the way to satisfy our needs.

**Comment by smoe** [comment]
Wow! This is more than I could possibly expect. Have many thanks!
Let me get the server up anyway [update, it is up on 95.216.141.130] as it is mostly routine and another excuse to contribute to [einstein@home](http://einsteinathome.org) at bit more. A public key sent to moeller at debian.org gives you access.

The bit of pain above server protects you from is to upgrade to Debian sid (aka "unstable") where all the newly accepted packages land for early adopters to find problems. For that I typically add
```
deb http://deb.debian.org/debian sid main contrib non-free
deb-src http://deb.debian.org/debian sid main contrib non-free
deb http://deb.debian.org/debian experimental main contrib non-free
deb-src http://deb.debian.org/debian experimental main contrib non-free
```
to /etc/apt/sources.list , apt-get update and apt-get dist-upgrade.

Together with
```
apt-get install build-essential fakeroot git gitk dh-python debfoster deborphan aptitude vim
```
and your build-dependencies
```
apt-get install python-numpy python3-numpy python-coloredlogs python3-coloredlogs python-click python3-click libpython-dev libpython3-dev cython cython3 zlib1g-dev dh-python zlib1g-dev
```
this should get you going. For installable Debian packages of cyvcf2 I cordially invite you to https://salsa.debian.org/med-team/cyvcf2 . Clone that repository, symbolically link that debian subdirectory into your regular github source tree and "fakeroot ./debian/rules binary" creates .deb files in the parent directory ... or fails while testing, I mean :) . 

What I have not yet done was to install Debian's htslib 1.8, so you can reset assured that is not interfering. For that please run "apt-get install -t experimental htslib-dev".

Cheers,

Steffen

**Comment by vladsaveliev** [comment]
Hi,

Adding `crypt` broke compilation under macos, see https://github.com/bioconda/bioconda-recipes/pull/11464

```
ld: library not found for -lcrypt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```

I tried to install manually without `-lcrypt` and it fixed it on my mac, I'm not having any other issues. Do you think it might be needed only for debian or only for linux by any chance? What if we add an if-else like `"libraries=['z', 'curl', 'ssl'] + (['crypt'] if platform.system() != 'Darwin' else [])` to skip it for macos?

Vlad
